//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/GameInput/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Com.JVL.GameInput
{
    public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay Mouse Interactions"",
            ""id"": ""980c9fb2-d958-4963-9ac2-c2daf3c37985"",
            ""actions"": [
                {
                    ""name"": ""UI Interactions"",
                    ""type"": ""Button"",
                    ""id"": ""4213e2b8-467e-4aa3-97b9-505d0b142fc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Environment Interactions"",
                    ""type"": ""Button"",
                    ""id"": ""aab6d6e0-f016-4020-9426-fe81999ffe01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7dc80f62-2f48-403e-ac5b-8d8541093628"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI Interactions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd182604-4e91-4741-9ee2-5070b258eb1d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI Interactions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10a80484-cc01-458d-b413-25507eb4c3ad"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Environment Interactions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97d57383-04c6-4c5e-a895-aaf43679f7ff"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Environment Interactions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Hero Skill"",
            ""id"": ""0a35b62a-977b-41e8-a11d-b9958f5213f1"",
            ""actions"": [
                {
                    ""name"": ""Basic Skills"",
                    ""type"": ""Button"",
                    ""id"": ""a0d2a715-2c66-433f-86ec-6a69dbf3b69d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Additional Skills"",
                    ""type"": ""Button"",
                    ""id"": ""349ac0e6-2c18-493a-9287-52043743344b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Teleport"",
                    ""type"": ""Button"",
                    ""id"": ""c8910206-76f5-476d-8a16-882ee1c436c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Items"",
                    ""type"": ""Button"",
                    ""id"": ""fd1efd79-543f-4bfd-b09a-d00806551aaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c804188e-1e1f-4253-a219-407caa0e95e9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bd28b8f-ce09-4d8f-af13-8792a93fc393"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d748d21e-2cd7-4cd7-a40a-a3c789d749ac"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4ddc9f8-7714-455c-80bf-869da32c6d29"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Basic Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f46348d-a4cb-4811-a39b-629f8cd7e9d2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Additional Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""116e2106-c6cb-4328-a155-6d706c43dcad"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Additional Skills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a0f602b-b706-46dd-8272-dccc68294c59"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb4bc13b-3127-41ea-b416-28fd91f68c29"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""617249f2-d408-40c9-a87c-9380ac3c59c2"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4ba6902-def8-4dea-87d8-c0716d5944ff"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f8e4adb-dccc-4d5d-9743-dd5fd2efd63e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd895119-61eb-40ef-a98d-170bf93dcd40"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d347f5d0-1bd9-47be-9bcb-8d4280222e66"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Items"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""1780ab17-140c-404a-8670-eb6a2baa0615"",
            ""actions"": [
                {
                    ""name"": ""Move Camera"",
                    ""type"": ""Value"",
                    ""id"": ""64607036-90bb-4f5a-aab0-823da745c9f9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""UpDownLeftRight"",
                    ""id"": ""1234c88b-600b-43ee-b655-67180c609b04"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Camera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7776c6a1-2aa2-4593-9cca-eb11d8085b18"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3be256fa-eec5-4a47-ab39-21c9e706eafa"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""68c3eecb-0820-4b28-a02e-9f79efcec4fc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5a7cc4b2-9063-4a4d-9e3a-ba4e7ee2c3a5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay Mouse Interactions
            m_GameplayMouseInteractions = asset.FindActionMap("Gameplay Mouse Interactions", throwIfNotFound: true);
            m_GameplayMouseInteractions_UIInteractions = m_GameplayMouseInteractions.FindAction("UI Interactions", throwIfNotFound: true);
            m_GameplayMouseInteractions_EnvironmentInteractions = m_GameplayMouseInteractions.FindAction("Environment Interactions", throwIfNotFound: true);
            // Hero Skill
            m_HeroSkill = asset.FindActionMap("Hero Skill", throwIfNotFound: true);
            m_HeroSkill_BasicSkills = m_HeroSkill.FindAction("Basic Skills", throwIfNotFound: true);
            m_HeroSkill_AdditionalSkills = m_HeroSkill.FindAction("Additional Skills", throwIfNotFound: true);
            m_HeroSkill_Teleport = m_HeroSkill.FindAction("Teleport", throwIfNotFound: true);
            m_HeroSkill_UseItems = m_HeroSkill.FindAction("Use Items", throwIfNotFound: true);
            // Camera
            m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
            m_Camera_MoveCamera = m_Camera.FindAction("Move Camera", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay Mouse Interactions
        private readonly InputActionMap m_GameplayMouseInteractions;
        private IGameplayMouseInteractionsActions m_GameplayMouseInteractionsActionsCallbackInterface;
        private readonly InputAction m_GameplayMouseInteractions_UIInteractions;
        private readonly InputAction m_GameplayMouseInteractions_EnvironmentInteractions;
        public struct GameplayMouseInteractionsActions
        {
            private @PlayerInputActions m_Wrapper;
            public GameplayMouseInteractionsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @UIInteractions => m_Wrapper.m_GameplayMouseInteractions_UIInteractions;
            public InputAction @EnvironmentInteractions => m_Wrapper.m_GameplayMouseInteractions_EnvironmentInteractions;
            public InputActionMap Get() { return m_Wrapper.m_GameplayMouseInteractions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayMouseInteractionsActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayMouseInteractionsActions instance)
            {
                if (m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface != null)
                {
                    @UIInteractions.started -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnUIInteractions;
                    @UIInteractions.performed -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnUIInteractions;
                    @UIInteractions.canceled -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnUIInteractions;
                    @EnvironmentInteractions.started -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnEnvironmentInteractions;
                    @EnvironmentInteractions.performed -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnEnvironmentInteractions;
                    @EnvironmentInteractions.canceled -= m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface.OnEnvironmentInteractions;
                }
                m_Wrapper.m_GameplayMouseInteractionsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @UIInteractions.started += instance.OnUIInteractions;
                    @UIInteractions.performed += instance.OnUIInteractions;
                    @UIInteractions.canceled += instance.OnUIInteractions;
                    @EnvironmentInteractions.started += instance.OnEnvironmentInteractions;
                    @EnvironmentInteractions.performed += instance.OnEnvironmentInteractions;
                    @EnvironmentInteractions.canceled += instance.OnEnvironmentInteractions;
                }
            }
        }
        public GameplayMouseInteractionsActions @GameplayMouseInteractions => new GameplayMouseInteractionsActions(this);

        // Hero Skill
        private readonly InputActionMap m_HeroSkill;
        private IHeroSkillActions m_HeroSkillActionsCallbackInterface;
        private readonly InputAction m_HeroSkill_BasicSkills;
        private readonly InputAction m_HeroSkill_AdditionalSkills;
        private readonly InputAction m_HeroSkill_Teleport;
        private readonly InputAction m_HeroSkill_UseItems;
        public struct HeroSkillActions
        {
            private @PlayerInputActions m_Wrapper;
            public HeroSkillActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @BasicSkills => m_Wrapper.m_HeroSkill_BasicSkills;
            public InputAction @AdditionalSkills => m_Wrapper.m_HeroSkill_AdditionalSkills;
            public InputAction @Teleport => m_Wrapper.m_HeroSkill_Teleport;
            public InputAction @UseItems => m_Wrapper.m_HeroSkill_UseItems;
            public InputActionMap Get() { return m_Wrapper.m_HeroSkill; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HeroSkillActions set) { return set.Get(); }
            public void SetCallbacks(IHeroSkillActions instance)
            {
                if (m_Wrapper.m_HeroSkillActionsCallbackInterface != null)
                {
                    @BasicSkills.started -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnBasicSkills;
                    @BasicSkills.performed -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnBasicSkills;
                    @BasicSkills.canceled -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnBasicSkills;
                    @AdditionalSkills.started -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnAdditionalSkills;
                    @AdditionalSkills.performed -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnAdditionalSkills;
                    @AdditionalSkills.canceled -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnAdditionalSkills;
                    @Teleport.started -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnTeleport;
                    @Teleport.performed -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnTeleport;
                    @Teleport.canceled -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnTeleport;
                    @UseItems.started -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnUseItems;
                    @UseItems.performed -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnUseItems;
                    @UseItems.canceled -= m_Wrapper.m_HeroSkillActionsCallbackInterface.OnUseItems;
                }
                m_Wrapper.m_HeroSkillActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @BasicSkills.started += instance.OnBasicSkills;
                    @BasicSkills.performed += instance.OnBasicSkills;
                    @BasicSkills.canceled += instance.OnBasicSkills;
                    @AdditionalSkills.started += instance.OnAdditionalSkills;
                    @AdditionalSkills.performed += instance.OnAdditionalSkills;
                    @AdditionalSkills.canceled += instance.OnAdditionalSkills;
                    @Teleport.started += instance.OnTeleport;
                    @Teleport.performed += instance.OnTeleport;
                    @Teleport.canceled += instance.OnTeleport;
                    @UseItems.started += instance.OnUseItems;
                    @UseItems.performed += instance.OnUseItems;
                    @UseItems.canceled += instance.OnUseItems;
                }
            }
        }
        public HeroSkillActions @HeroSkill => new HeroSkillActions(this);

        // Camera
        private readonly InputActionMap m_Camera;
        private ICameraActions m_CameraActionsCallbackInterface;
        private readonly InputAction m_Camera_MoveCamera;
        public struct CameraActions
        {
            private @PlayerInputActions m_Wrapper;
            public CameraActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @MoveCamera => m_Wrapper.m_Camera_MoveCamera;
            public InputActionMap Get() { return m_Wrapper.m_Camera; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
            public void SetCallbacks(ICameraActions instance)
            {
                if (m_Wrapper.m_CameraActionsCallbackInterface != null)
                {
                    @MoveCamera.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveCamera;
                    @MoveCamera.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveCamera;
                    @MoveCamera.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMoveCamera;
                }
                m_Wrapper.m_CameraActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @MoveCamera.started += instance.OnMoveCamera;
                    @MoveCamera.performed += instance.OnMoveCamera;
                    @MoveCamera.canceled += instance.OnMoveCamera;
                }
            }
        }
        public CameraActions @Camera => new CameraActions(this);
        public interface IGameplayMouseInteractionsActions
        {
            void OnUIInteractions(InputAction.CallbackContext context);
            void OnEnvironmentInteractions(InputAction.CallbackContext context);
        }
        public interface IHeroSkillActions
        {
            void OnBasicSkills(InputAction.CallbackContext context);
            void OnAdditionalSkills(InputAction.CallbackContext context);
            void OnTeleport(InputAction.CallbackContext context);
            void OnUseItems(InputAction.CallbackContext context);
        }
        public interface ICameraActions
        {
            void OnMoveCamera(InputAction.CallbackContext context);
        }
    }
}
